export const GET_EXP_SUMMARY_DATA = "GET_EXP_SUMMARY_DATA";
export const SET_EXP_SUMMARY_DATA_LOADING = "SET_EXP_SUMMARY_DATA_LOADING";
export const EXP_SUMMARY_DATA_ERROR = "EXP_SUMMARY_DATA_ERROR";

//get exp demandwise data
export const GET_EXP_DEMANDWISE_DATA = "GET_EXP_DEMANDWISE_DATA";
export const SET_DATA_LOADING_EXP_DEMANDWISE = "SET_DATA_LOADING_EXP_DEMANDWISE";
export const EXP_DEMANDWISE_DATA_ERROR = "EXP_DEMANDWISE_DATA_ERROR";

//get exp demandwise filters
export const GET_EXP_DEMANDWISE_FILTERS_DATA = "GET_EXP_DEMANDWISE_FILTERS_DATA";
export const UPDATE_EXP_DEMANDWISE_FILTERS_DATA = "UPDATE_EXP_DEMANDWISE_FILTERS_DATA";
export const EXP_DEMANDWISE_FILTERS_DATA_ERROR = "EXP_DEMANDWISE_FILTERS_DATA_ERROR";
export const SET_DATA_LOADING_EXP_DEMANDWISE_FILTERS = "SET_DATA_LOADING_EXP_DEMANDWISE_FILTERS";

//get exp districtwise data
export const DISTRICTWISE_SWITCH_ACTIVE_VIZ_IDX = "DISTRICTWISE_SWITCH_ACTIVE_VIZ_IDX";
export const GET_EXP_DISTRICTWISE_DATA = "GET_EXP_DISTRICTWISE_DATA";
export const HYDRATE_EXP_DISTRICTWISE_DATA_FROM_INITDATA = "HYDRATE_EXP_DISTRICTWISE_DATA_FROM_INITDATA";
export const SET_DATA_LOADING_EXP_DISTRICTWISE = "SET_DATA_LOADING_EXP_DISTRICTWISE";
export const EXP_DISTRICTWISE_DATA_ERROR = "EXP_DISTRICTWISE_DATA_ERROR";
export const RESET_ACTIVE_FILTERS_AND_DATE_RANGE_DISTRICTWISE = "RESET_ACTIVE_FILTERS_AND_DATE_RANGE_DISTRICTWISE";

//get exp districtwise filters
export const GET_EXP_DISTRICTWISE_FILTERS_DATA = "GET_EXP_DISTRICTWISE_FILTERS_DATA";
export const EXP_DISTRICTWISE_FILTERS_DATA_ERROR = "EXP_DISTRICTWISE_FILTERS_DATA_ERROR";
export const SET_DATA_LOADING_EXP_DISTRICTWISE_FILTERS = "SET_DATA_LOADING_EXP_DISTRICTWISE_FILTERS";
export const UPDATE_EXP_DISTRICTWISE_FILTERS_DATA = "UPDATE_EXP_DISTRICTWISE_FILTERS_DATA";

//get exp schemes data
export const GET_EXP_SCHEMES_DATA = "GET_EXP_SCHEMES_DATA";
export const SET_DATA_LOADING_EXP_SCHEMES = "SET_DATA_LOADING_EXP_SCHEMES";
export const RESET_ACTIVE_FILTERS_AND_DATE_RANGE_SCHEMES = "RESET_ACTIVE_FILTERS_AND_DATE_RANGE_SCHEMES"
export const EXP_SCHEMES_DATA_ERROR = "EXP_SCHEMES_DATA_ERROR";
export const HYDRATE_SCHEMES_DATA_FROM_INITDATA = "HYDRATE_SCHEMES_DATA_FROM_INITDATA";

//get exp schemes filters
export const GET_EXP_SCHEMES_FILTERS_DATA = "GET_EXP_SCHEMES_FILTERS_DATA";
export const EXP_SCHEMES_FILTERS_DATA_ERROR = "EXP_SCHEMES_FILTERS_DATA_ERROR";
export const SET_DATA_LOADING_EXP_SCHEMES_FILTERS = "SET_DATA_LOADING_EXP_SCHEMES_FILTERS";
export const UPDATE_EXP_SCHEMES_FILTERS_DATA = "UPDATE_EXP_SCHEMES_FILTERS_DATA";

//get receipts data
export const GET_RECEIPTS_DATA = "GET_RECEIPTS_DATA";
export const SET_DATA_LOADING_RECEIPTS = "SET_DATA_LOADING_RECEIPTS";
export const RECEIPTS_DATA_ERROR = "RECEIPTS_DATA_ERROR";

//get receipts filters
export const GET_RECEIPTS_FILTERS_DATA = "GET_RECEIPTS_FILTERS_DATA";
export const UPDATE_RECEIPTS_FILTERS_DATA = "UPDATE_RECEIPTS_FILTERS_DATA";
export const RECEIPTS_FILTERS_DATA_ERROR = "RECEIPTS_FILTERS_DATA_ERROR";
export const SET_LOADING_RECEIPTS_FILTERS = "SET_LOADING_RECEIPTS_FILTERS";
